//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNRD.Modkist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PreloadedDependencies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreloadedDependencies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TNRD.Modkist.PreloadedDependencies", typeof(PreloadedDependencies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ModId&quot;:2052599,&quot;Stamp&quot;:1691151745,&quot;Dependencies&quot;:[2647797,3082296]},{&quot;ModId&quot;:2058138,&quot;Stamp&quot;:1653136326,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2077304,&quot;Stamp&quot;:1665485298,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2080039,&quot;Stamp&quot;:1670220811,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2080358,&quot;Stamp&quot;:1670214358,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2080390,&quot;Stamp&quot;:1665485155,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2080570,&quot;Stamp&quot;:1665485168,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2080638,&quot;Stamp&quot;:1665485180,&quot;Dependencies&quot;:[]},{&quot;ModId&quot;:2080736,&quot;Stamp&quot;:1670242607,&quot;Dependencies&quot;:[]},{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
